using InfinityScript;
using System.Collections.Generic;
using static InfinityScript.GSCFunctions;

namespace LoggingUtil
{
    public class LoggingUtil : BaseScript
    {
        private CustomLogger customLog = new CustomLogger();
        private bool sv_HWIDProtect;
        private HashSet<string> IPList = new HashSet<string>();
        private HashSet<string> HWIDList = new HashSet<string>();

        /*
         * Every time a player connects all his personal data is sent to the Logger
         */
        public LoggingUtil()
        {
            SetDvarIfUninitialized("sv_HWIDProtect", "1");
            sv_HWIDProtect = GetDvarInt("sv_HWIDProtect") == 1;
            IPrintLn("Advanced Logger Made by ^1Diavolo ^7for ^6IS ^71.5.0");
            Utilities.PrintToConsole("Check the folder DiavoloLogs to see all the logs generated by this script <3");

            PlayerConnected += (Entity player) =>
            {
                customLog.Info("Player {0} connected with IP: {1} with HWID: {2} with GUID: {3} with XUID: {4} with ClanTag: {5} with Title: {6}", player.Name, player.IP.Address, player.HWID, player.GUID, player.GetXUID(), player.GetClanTag(), player.GetPlayerTitle());
                IPList.Add(player.IP.Address.ToString());
                HWIDList.Add(player.HWID);
            };

            PlayerDisconnected += (Entity player) =>
            {
                bool IP = IPList.Remove(player.IP.Address.ToString());
                bool HWID = HWIDList.Remove(player.HWID);
                customLog.Info("Player {0} disconnected with IP: {1} with HWID: {2} Result: {3} {4} <- All must be True", player.Name, player.IP.Address, player.HWID, IP, HWID);
            };
        }

        public override string OnPlayerRequestConnection(string playerName, string playerHWID, string playerXUID, string playerIP, string playerSteamID, string playerXNAddress)
        {
            if (sv_HWIDProtect)
            {
                string[] IPArray = playerIP.Split('\\');
                string[] NameArray = playerName.Split('\\');
                string[] HWIDArray = playerHWID.Split('\\');

                string MyPlayerIP = IPArray[1];
                string MyName = NameArray[1];
                string MyHWID = HWIDArray[1].ToUpper();

                if (IPList.Contains(MyPlayerIP))
                {
                    customLog.Info("Player {0} connecting with IP: {1} with HWID: {2} was kicked because he has the same IP of another player but different HWID", MyName, MyPlayerIP, MyHWID);
                    return "Same IP, different HWID. Is the cat stepping on the keyboard? Expect to be ^1Banned";
                }

                if (HWIDList.Contains(MyHWID))
                {
                    customLog.Info("Player {0} connecting with IP: {1} with HWID: {2} was kicked because he has the same HWID of another online player", MyName, MyPlayerIP, MyHWID);
                    return "Same HWID of another online player. Is the cat stepping on the keyboard? Expect to be ^1Banned";
                }
            }
            return null;
        }
    }
}
